version: "2"

linters:
  default: none
  enable:
    - errorlint
    - gocritic
    - gosec
    - govet
    - modernize
    - revive
    - staticcheck
    - testifylint
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
      - linters:
          - revive
        text: "^(exported|package-comments):"
